package com.noop.data

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * SHARED Room<->GRDB SCHEMA ORACLE — the Kotlin half of a cross-platform schema drift guard (#775).
 *
 * `src/test/resources/schema_oracle.json` pins, for every table, the columns **in order** with their
 * SQLite type affinity / NOT NULL / DEFAULT, the primary-key composition, and the explicit indices. The
 * IDENTICAL file is committed at `Packages/WhoopStore/Tests/WhoopStoreTests/Resources/schema_oracle.json`,
 * and the Swift `SchemaOracleTests` runs the real GRDB migrator and asserts `PRAGMA table_info` against
 * it. This half reads the schema **Room itself generates**.
 *
 * How a plain JVM test can see Room's schema at all: `@Database(exportSchema = true)` plus the
 * `room.schemaLocation` KSP argument in `app/build.gradle.kts` make Room's processor write one JSON file
 * per database version describing the exact `CREATE TABLE` it emits — every column in declaration order
 * with affinity / NOT NULL / default, the primary key and the indices. That file is a plain build
 * artifact, so this needs no device, no emulator and no Robolectric. It is written into the build
 * directory and deliberately NOT committed: the committed artifact is the shared oracle, Room's JSON is
 * the derived answer, regenerated by KSP on every build.
 *
 * The oracle records the **iOS/GRDB shape as canonical** (macOS is the reference implementation). Every
 * way Android differs today is spelled out as an `android` / `iosAbsent` / `androidColumnOrder` override
 * naming a key in `divergenceReasons`. So this test fails in BOTH directions: a NEW divergence fails
 * because Android no longer matches canonical, and a FIXED one fails because the recorded override is no
 * longer true. The ledger can only shrink deliberately.
 *
 * Follows the `decoder_oracle.json` idiom (#869) rather than adding a third mechanism.
 */
class SchemaOracleTest {

    // ---------------------------------------------------------------- fixtures

    private fun loadOracle(): JSONObject {
        val stream = javaClass.classLoader!!.getResourceAsStream("schema_oracle.json")
        assertNotNull("schema_oracle.json missing from test classpath", stream)
        return JSONObject(stream!!.bufferedReader().use { it.readText() })
    }

    /** Room's exported schema for the version the oracle pins, plus a check that it IS the newest one. */
    private fun loadRoomSchema(expectedVersion: Int): JSONObject {
        val location = System.getProperty("room.schemaLocation")
        assertNotNull(
            "room.schemaLocation system property not set — see the `ksp { arg(\"room.schemaLocation\", …) }` " +
                "and `tasks.withType<Test>` blocks in app/build.gradle.kts",
            location,
        )
        val dir = File(location, "com.noop.data.WhoopDatabase")
        assertTrue(
            "Room schema export directory missing at $dir. It is written by KSP from " +
                "@Database(exportSchema = true) + the room.schemaLocation arg and snapshotted by the " +
                "syncRoomSchemaSnapshot task; run ./gradlew :app:syncRoomSchemaSnapshot if this is a " +
                "stale build directory.",
            dir.isDirectory,
        )
        val versions = dir.listFiles { f -> f.name.endsWith(".json") }
            .orEmpty()
            .mapNotNull { it.name.removeSuffix(".json").toIntOrNull() }
        assertTrue("no Room schema JSON exported under $dir", versions.isNotEmpty())
        assertEquals(
            "schema_oracle.json pins roomVersion=$expectedVersion but the newest exported Room schema is " +
                "${versions.max()} — a @Database version bump needs the oracle updated in the same change.",
            expectedVersion,
            versions.max(),
        )
        val schema = JSONObject(File(dir, "$expectedVersion.json").readText()).getJSONObject("database")
        assertEquals("exported schema's own version field", expectedVersion, schema.getInt("version"))
        return schema
    }

    /**
     * SQLite type affinity from a declared column type (datatype3 §3.1). Identical to the Swift half's
     * `sqliteAffinity`. GRDB writes DOUBLE where Room writes REAL — both REAL affinity, so the rule
     * collapses a spelling difference that is not drift, while keeping BOOLEAN (NUMERIC) distinct from
     * INTEGER, which genuinely is.
     */
    private fun sqliteAffinity(declaredType: String): String {
        val t = declaredType.uppercase()
        return when {
            t.contains("INT") -> "INTEGER"
            t.contains("CHAR") || t.contains("CLOB") || t.contains("TEXT") -> "TEXT"
            t.contains("BLOB") || t.isEmpty() -> "BLOB"
            t.contains("REAL") || t.contains("FLOA") || t.contains("DOUB") -> "REAL"
            else -> "NUMERIC"
        }
    }

    private data class Col(val name: String, val affinity: String, val notNull: Boolean, val default: String?)
    private data class Idx(val name: String, val unique: Boolean, val columns: List<String>)
    private data class Tbl(val columns: List<Col>, val primaryKey: List<String>, val indices: List<Idx>)

    private fun roomTables(schema: JSONObject): Map<String, Tbl> {
        val entities = schema.getJSONArray("entities")
        return (0 until entities.length()).associate { i ->
            val e = entities.getJSONObject(i)
            val fields = e.getJSONArray("fields")
            val cols = (0 until fields.length()).map { j ->
                val f = fields.getJSONObject(j)
                Col(
                    name = f.getString("columnName"),
                    affinity = sqliteAffinity(f.getString("affinity")),
                    notNull = f.getBoolean("notNull"),
                    default = if (f.has("defaultValue")) f.getString("defaultValue") else null,
                )
            }
            val indices = e.optJSONArray("indices").orEmptyArray().let { arr ->
                (0 until arr.length()).map { j ->
                    val idx = arr.getJSONObject(j)
                    Idx(idx.getString("name"), idx.getBoolean("unique"), idx.getJSONArray("columnNames").strings())
                }.sortedBy { it.name }
            }
            e.getString("tableName") to Tbl(cols, e.getJSONObject("primaryKey").getJSONArray("columnNames").strings(), indices)
        }
    }

    /** The columns the oracle expects ANDROID to have: canonical shape + every declared override. */
    private fun androidExpectedColumns(table: JSONObject): List<Col> {
        val columns = table.getJSONArray("columns")
        val byName = LinkedHashMap<String, Col>()
        for (i in 0 until columns.length()) {
            val c = columns.getJSONObject(i)
            if (c.optBoolean("androidAbsent", false)) continue
            var col = Col(
                name = c.getString("name"),
                affinity = c.getString("affinity"),
                notNull = c.getBoolean("notNull"),
                default = if (c.isNull("default")) null else c.getString("default"),
            )
            c.optJSONObject("android")?.let { ov ->
                col = col.copy(
                    affinity = if (ov.has("affinity")) ov.getString("affinity") else col.affinity,
                    notNull = if (ov.has("notNull")) ov.getBoolean("notNull") else col.notNull,
                    default = if (ov.has("default")) (if (ov.isNull("default")) null else ov.getString("default")) else col.default,
                )
            }
            byName[col.name] = col
        }
        val order = table.optJSONArray("androidColumnOrder")?.strings() ?: return byName.values.toList()
        return order.map { byName.getValue(it) }
    }

    // ---------------------------------------------------------------- tests

    /**
     * Every Room table matches the oracle: column names **in order**, affinity, NOT NULL, DEFAULT,
     * primary-key composition and explicit indices — after applying the declared divergences. Column
     * ORDER is asserted because CLAUDE.md's parity contract calls it out specifically: Room's generated
     * `CREATE TABLE` follows entity field order, while a GRDB `ALTER TABLE ADD COLUMN` can only append.
     */
    @Test
    fun roomSchemaMatchesOracle() {
        val oracle = loadOracle()
        val tables = oracle.getJSONObject("tables")
        val room = roomTables(loadRoomSchema(oracle.getInt("roomVersion")))
        val problems = mutableListOf<String>()

        for (name in tables.keys().asSequence().sorted()) {
            val spec = tables.getJSONObject(name)
            if (spec.getString("platform") == "ios_only") {
                if (room.containsKey(name)) {
                    problems += "$name: declared ios_only in schema_oracle.json but Room now declares an " +
                        "entity for it — it gained a twin: move it to platform \"both\" and pin its columns."
                }
                continue
            }
            val actual = room[name]
            if (actual == null) {
                problems += "$name: pinned by schema_oracle.json but no Room entity declares it"
                continue
            }

            val expected = androidExpectedColumns(spec)
            if (expected.map { it.name } != actual.columns.map { it.name }) {
                problems += "$name: Room column ORDER/SET differs from schema_oracle.json\n" +
                    "      oracle: ${expected.map { it.name }}\n" +
                    "      room:   ${actual.columns.map { it.name }}"
            }
            for ((want, got) in expected.zip(actual.columns)) {
                if (want.name != got.name) continue
                if (want.affinity != got.affinity) {
                    problems += "$name.${want.name}: type affinity — oracle ${want.affinity}, room ${got.affinity}"
                }
                if (want.notNull != got.notNull) {
                    problems += "$name.${want.name}: NOT NULL — oracle ${want.notNull}, room ${got.notNull}"
                }
                if (want.default != got.default) {
                    problems += "$name.${want.name}: DEFAULT — oracle ${want.default ?: "none"}, " +
                        "room ${got.default ?: "none"}"
                }
            }
            val wantPk = spec.getJSONArray("primaryKey").strings()
            if (wantPk != actual.primaryKey) {
                problems += "$name: PRIMARY KEY — oracle $wantPk, room ${actual.primaryKey}"
            }
            val wantIdx = spec.getJSONArray("indices").let { arr ->
                (0 until arr.length()).map { i ->
                    val o = arr.getJSONObject(i)
                    Idx(o.getString("name"), o.getBoolean("unique"), o.getJSONArray("columns").strings())
                }.sortedBy { it.name }
            }
            if (wantIdx != actual.indices) {
                problems += "$name: indices — oracle $wantIdx, room ${actual.indices}"
            }
        }
        assertTrue(
            "Room schema drifted from schema_oracle.json (${problems.size}). A divergence must be either " +
                "fixed on the drifted side or written down in the fixture with a divergenceReasons entry:\n" +
                "  - " + problems.joinToString("\n  - "),
            problems.isEmpty(),
        )
    }

    /**
     * The oracle cannot quietly stop covering a table: every Room entity must be pinned. This is what
     * fails when a new entity lands on Android with no GRDB twin and no explicit `android_only` entry.
     */
    @Test
    fun oracleCoversEveryRoomTable() {
        val oracle = loadOracle()
        val pinned = oracle.getJSONObject("tables").keys().asSequence().toSet()
        val unpinned = (roomTables(loadRoomSchema(oracle.getInt("roomVersion"))).keys - pinned).sorted()
        assertTrue(
            "Room tables missing from schema_oracle.json: $unpinned. A new table needs a GRDB twin (or " +
                "an explicit android_only entry) before it can land.",
            unpinned.isEmpty(),
        )
    }

    /**
     * Room's version is pinned alongside the GRDB migration identifiers, so neither store can gain a
     * migration without the author opening this fixture and looking at the other side. GRDB keys
     * migrations by NAME and applies them in registration order; Room keys by integer version, so the
     * only thing that can be compared mechanically is the RESULTING schema — which is what the tests
     * above do. Pinning the two identifier spaces is what forces them to be re-checked together.
     *
     * The one sanctioned exception is a DECLARED lineage. A fork that numbered its own migrations before
     * upstream reached those numbers cannot renumber its way out — GRDB keys by identifier string, so
     * renaming one makes it read as un-applied on a device that already ran it. Such a fork lists its
     * identifiers under `grdbMigrationLineages`; everything NOT listed is the baseline lineage and is
     * still held to exactly v1..vN. An UNDECLARED collision still fails, which is the #369-vs-#475 case.
     * Mirrors `testGrdbMigrationIdentifiersAreUniqueAndSequential` in the Swift half.
     */
    @Test
    fun pinnedMigrationIdentifiersAreCoherent() {
        val oracle = loadOracle()
        val grdb = oracle.getJSONArray("grdbMigrations").strings()
        assertEquals("duplicate GRDB migration identifier in schema_oracle.json", grdb.size, grdb.toSet().size)

        // A declared lineage must be true (every member pinned) and self-consistent (its own vN strictly
        // increasing), so the ledger can only shrink deliberately — same rule the divergence reasons live by.
        val lineages = oracle.optJSONObject("grdbMigrationLineages") ?: JSONObject()
        val claimedBy = HashMap<String, String>()
        for (name in lineages.keys().asSequence().sorted()) {
            val migrations = lineages.getJSONObject(name).getJSONArray("migrations").strings()
            assertTrue("lineage '$name' declares no migrations — delete it", migrations.isNotEmpty())
            val numbers = migrations.map { id ->
                val other = claimedBy.put(id, name)
                assertTrue("'$id' is claimed by both lineage '$other' and '$name'", other == null)
                assertTrue(
                    "lineage '$name' declares '$id', which is not in grdbMigrations — a lineage entry that " +
                        "stopped being true must be deleted, not left to rot",
                    grdb.contains(id),
                )
                val n = migrationVersion(id)
                assertNotNull("lineage '$name' member '$id' is not of the form v<N>[-slug]", n)
                n!!
            }
            numbers.zipWithNext { a, b ->
                assertTrue(
                    "lineage '$name' goes v$a then v$b — a lineage numbers its own migrations, so its vN " +
                        "must strictly increase",
                    b > a,
                )
            }
        }

        grdb.filterNot { claimedBy.containsKey(it) }.forEachIndexed { i, id ->
            assertEquals(
                "GRDB migration '$id' claims v${migrationVersion(id)} but is #${i + 1} in the BASELINE " +
                    "lineage (grdbMigrations minus every lineage grdbMigrationLineages declares) — two " +
                    "migrations claiming the same vN, or a gap, makes the GRDB-name <-> Room-version " +
                    "mapping ambiguous. Renumber before merging, or, if the identifier already shipped and " +
                    "renaming it would wedge a live database, declare it in grdbMigrationLineages.",
                i + 1,
                migrationVersion(id),
            )
        }
        // loadRoomSchema asserts the exported version equals this; call it so the check is not vacuous.
        loadRoomSchema(oracle.getInt("roomVersion"))
    }

    /** The `N` of a `v<N>[-slug]` migration identifier, or null if it is not of that form. */
    private fun migrationVersion(id: String): Int? =
        id.removePrefix("v").takeWhile { it.isDigit() }.toIntOrNull()

    /**
     * The Android and Swift copies of the oracle MUST be byte-identical, so neither platform can edit its
     * fixture without the other. Skips gracefully if the Swift tree isn't present.
     */
    @Test
    fun oracleCopiesAreIdentical() {
        val androidBytes = javaClass.classLoader!!
            .getResourceAsStream("schema_oracle.json")!!
            .use { it.readBytes() }

        // Gradle runs unit tests with the module dir (android/app) or repo root as user.dir; try both.
        val userDir = File(System.getProperty("user.dir"))
        val swiftFile = listOf(
            File(userDir, "Packages/WhoopStore/Tests/WhoopStoreTests/Resources/schema_oracle.json"),
            File(userDir, "../../Packages/WhoopStore/Tests/WhoopStoreTests/Resources/schema_oracle.json"),
        ).firstOrNull { it.exists() }
        org.junit.Assume.assumeTrue(
            "swift oracle copy not found from user.dir=$userDir — skipping cross-copy identity check",
            swiftFile != null,
        )
        assertTrue(
            "schema_oracle.json copies differ — keep the Android and Swift copies in lockstep",
            androidBytes.contentEquals(swiftFile!!.readBytes()),
        )
    }
}

private fun JSONArray?.orEmptyArray(): JSONArray = this ?: JSONArray()
private fun JSONArray.strings(): List<String> = (0 until length()).map { getString(it) }
