#!/usr/bin/env python3
"""Inject German (de) translations into Strand/Resources/Localizable.xcstrings.

Reads the English (en) base values and adds a `de` stringUnit for each key.
Format placeholders (%@, %lld, %%) are preserved. Pure symbol / placeholder-only
strings are passed through unchanged. Re-runnable: existing `de` units are
overwritten so this file stays the source of truth for the German translation.
"""
import json
from pathlib import Path

CATALOG = Path("Strand/Resources/Localizable.xcstrings")

# English key -> German value. Keys must match the catalog exactly.
DE: dict[str, str] = {
    # Symbols / pure placeholders — identical in German.
    "—": "—",
    "·": "·",
    "· %@": "· %@",
    "/ %lld": "/ %lld",
    "%@": "%@",
    "%@ – %@": "%@ – %@",
    "%@ · %@": "%@ · %@",
    "%@ · n = %lld": "%@ · n = %lld",
    "%@ / %@": "%@ / %@",
    "%@ %@": "%@ %@",
    "%@ ↔ %@": "%@ ↔ %@",
    "%@, %@%@": "%@, %@%@",
    "%@%@": "%@%@",
    "%lld": "%lld",
    "%lld / %lld": "%lld / %lld",
    "•": "•",
    "✓": "✓",
    "r = %@": "r = %@",
    "v%@": "v%@",
    "NOOP": "NOOP",
    "NOOP %@": "NOOP %@",

    # Units / short tokens.
    "% Max": "% Max",
    "bpm": "bpm",
    "BPM": "BPM",
    "Δ vs prev": "Δ vs. vorher",

    # Format strings.
    "%@ versus %@, r equals %@, %lld days": "%@ gegen %@, r gleich %@, %lld Tage",
    "%@ wrist alerts": "%@ Handgelenk-Hinweise",
    "%@, correlation %@, %lld days": "%@, Korrelation %@, %lld Tage",
    "%@, range %@ to %@": "%@, Bereich %@ bis %@",
    "%@: %@ last night%@": "%@: %@ letzte Nacht%@",
    "%lld app%@ on": "%lld App%@ aktiv",
    "%lld breaths": "%lld Atemzüge",
    "%lld days · %lld sleeps stored": "%lld Tage · %lld Schlafphasen gespeichert",
    "%lld frame%@ captured this session.": "%lld Frame%@ in dieser Sitzung erfasst.",
    "%lld min": "%lld Min",
    "%lld of %lld nights": "%lld von %lld Nächten",
    "%lld overlapping days · %@ %@ correlation": "%lld überlappende Tage · %@ %@ Korrelation",
    "%lld–%lld%@ · step %lld": "%lld–%lld%@ · Schritt %lld",
    "%@ is free and always will be. If it's useful to you, you can chip in to help with development and testing costs. Totally optional.": "%@ ist kostenlos und bleibt es. Wenn es dir nützt, kannst du etwas zu den Entwicklungs- und Testkosten beitragen. Völlig freiwillig.",
    "Age, %lld years": "Alter, %lld Jahre",
    "Auto · %lld bpm (Tanaka)": "Automatisch · %lld bpm (Tanaka)",
    "Battery %lld%%": "Akku %lld%%",
    "Battery %lld%% · Charging": "Akku %lld%% · Lädt",
    "Choose the buzz pattern for %@": "Vibrationsmuster für %@ wählen",
    "Coach said: %@": "Coach sagte: %@",
    "Copy %@ address": "%@-Adresse kopieren",
    "Email %@": "E-Mail %@",
    "Error: %@": "Fehler: %@",
    "Estimated max heart rate · %lld bpm": "Geschätzte maximale Herzfrequenz · %lld bpm",
    "Fetch the available models from %@ using your saved key": "Verfügbare Modelle von %@ mit deinem gespeicherten Schlüssel abrufen",
    "Heart rate %lld beats per minute": "Herzfrequenz %lld Schläge pro Minute",
    "Max heart rate override, %@": "Manuelle maximale Herzfrequenz, %@",
    "Mean %@": "Mittelwert %@",
    "No data for these metrics in %@. Widen the range or pick metrics you've logged.": "Keine Daten für diese Metriken in %@. Erweitere den Bereich oder wähle Metriken, die du erfasst hast.",
    "Not enough overlapping days between these metrics in %@. Widen the range.": "Nicht genug überlappende Tage zwischen diesen Metriken in %@. Erweitere den Bereich.",
    "Nothing in the catalog moves clearly with %@ over this window. Widen the range to surface relationships.": "Nichts im Katalog bewegt sich in diesem Zeitraum klar mit %@. Erweitere den Bereich, um Zusammenhänge sichtbar zu machen.",
    "of 3 · %@": "von 3 · %@",
    "Paste your %@ API key": "Füge deinen %@-API-Schlüssel ein",
    "Pearson r · %@": "Pearson r · %@",
    "Questions, feedback, bugs — %@": "Fragen, Feedback, Fehler — %@",
    "Reading your %@…": "%@ wird gelesen…",
    "Remove %@": "%@ entfernen",
    "Scan with any %@ wallet": "Mit einer beliebigen %@-Wallet scannen",
    "Show %@ donation address": "%@-Spendenadresse anzeigen",
    "Sleep stage breakdown: deep %lld percent, light %lld percent, REM %lld percent, awake %lld percent": "Schlafphasen-Aufschlüsselung: Tief %lld Prozent, Leicht %lld Prozent, REM %lld Prozent, Wach %lld Prozent",
    "Stress · %@": "Stress · %@",
    "Stress %@ of 3, %@": "Stress %@ von 3, %@",
    "Suggested prompt: %@": "Vorgeschlagene Frage: %@",
    "Test %@ buzz": "%@-Testvibration",
    "This is the only feature that leaves your Mac — it sends a summary of your metrics to %@ using your own key. Nothing is sent until you ask.": "Dies ist die einzige Funktion, die deinen Mac verlässt — sie sendet eine Zusammenfassung deiner Metriken mit deinem eigenen Schlüssel an %@. Es wird nichts gesendet, bis du es anforderst.",
    "What moves your %@": "Was deine %@ beeinflusst",
    "You said: %@": "Du sagtest: %@",

    # Sentences / labels.
    "A private window into your recovery, sleep and strain — read straight from your strap, kept only on this Mac.": "Ein privater Blick auf deine Erholung, deinen Schlaf und deine Belastung — direkt vom Strap gelesen und nur auf diesem Mac gespeichert.",
    "A standalone companion for your WHOOP. Everything stays on this device — your history, your live stream, your numbers. Nothing is uploaded. NOOP is an independent, experimental project, not the WHOOP app.": "Ein eigenständiger Begleiter für dein WHOOP. Alles bleibt auf diesem Gerät — deine Historie, dein Live-Stream, deine Werte. Nichts wird hochgeladen. NOOP ist ein unabhängiges, experimentelles Projekt, nicht die WHOOP-App.",
    "About": "Über",
    "Active energy": "Aktive Energie",
    "Activity": "Aktivität",
    "Activity & Energy": "Aktivität & Energie",
    "Activity Breakdown": "Aktivitätsaufschlüsselung",
    "Acute (7-day) vs chronic (28-day) training load. 0.8–1.3 is the sweet spot.": "Akute (7 Tage) vs. chronische (28 Tage) Trainingslast. 0,8–1,3 ist der ideale Bereich.",
    "Add a metric to compare": "Eine Metrik zum Vergleich hinzufügen",
    "Add metric": "Metrik hinzufügen",
    "Age": "Alter",
    "All Sessions": "Alle Sitzungen",
    "ALL YOUR DATA · NONE OF THE CLOUD": "ALL DEINE DATEN · NICHTS IN DER CLOUD",
    "all your data, none of the cloud": "all deine Daten, nichts in der Cloud",
    "Any amount helps. Thank you — genuinely.": "Jeder Betrag hilft. Danke — wirklich.",
    "API key": "API-Schlüssel",
    "Apple": "Apple",
    "Apple Health": "Apple Health",
    "Ask about your recovery, strain, sleep and workouts — grounded in your own numbers.": "Frage nach deiner Erholung, Belastung, deinem Schlaf und deinen Workouts — basierend auf deinen eigenen Werten.",
    "Ask Coach about your data…": "Frage den Coach zu deinen Daten…",
    "Ask your first question": "Stelle deine erste Frage",
    "Asleep": "Schlafend",
    "Asleep avg": "Schlaf Ø",
    "Asleep duration": "Schlafdauer",
    "At a glance": "Auf einen Blick",
    "Auto": "Automatisch",
    "Automations": "Automationen",
    "Autonomic load from HRV and resting heart rate": "Autonome Last aus HRV und Ruheherzfrequenz",
    "Average": "Durchschnitt",
    "Avg": "Ø",
    "Awake": "Wach",
    "Back": "Zurück",
    "Backup & restore": "Sicherung & Wiederherstellung",
    "Behaviour Effects": "Verhaltenseffekte",
    "Blood oxygen": "Blutsauerstoff",
    "Blood Oxygen": "Blutsauerstoff",
    "BMI": "BMI",
    "Body Composition": "Körperzusammensetzung",
    "Body fat": "Körperfett",
    "Body Fat": "Körperfett",
    "Bond your strap on the Live screen to feel the transitions hands-free.": "Verbinde deinen Strap im Live-Bildschirm, um die Übergänge freihändig zu spüren.",
    "Breathe": "Atmen",
    "Building from your strap": "Wird von deinem Strap aufgebaut",
    "Built on": "Basiert auf",
    "Buzz cues on": "Vibrationshinweise an",
    "Buzz strap": "Strap vibrieren",
    "Buzz your strap when these apps notify you. Everything runs on this Mac.": "Lass deinen Strap vibrieren, wenn diese Apps dich benachrichtigen. Alles läuft auf diesem Mac.",
    "Buzzes your wrist": "Vibriert an deinem Handgelenk",
    "By sport": "Nach Sportart",
    "Calendar": "Kalender",
    "Calibrating": "Kalibrierung",
    "Calm time": "Ruhezeit",
    "Calories": "Kalorien",
    "Cardiac": "Herz",
    "Category": "Kategorie",
    "Choose export…": "Export wählen…",
    "Choose export.zip…": "export.zip wählen…",
    "Clear": "Löschen",
    "Close": "Schließen",
    "Close Support": "Support schließen",
    "Coach": "Coach",
    "Coach is thinking": "Coach denkt nach",
    "Coach is thinking…": "Coach denkt nach…",
    "Coach reads a summary of your last two weeks plus 30-day averages and recent workouts, then answers in plain language. Try a suggestion below.": "Der Coach liest eine Zusammenfassung deiner letzten zwei Wochen sowie 30-Tage-Durchschnitte und aktuelle Workouts und antwortet dann in klarer Sprache. Probiere einen Vorschlag unten aus.",
    "Coach uses your own API key. Pick a provider, paste a key, and choose a model. Your key is stored securely in the macOS Keychain and never leaves your Mac except as the request you make.": "Der Coach nutzt deinen eigenen API-Schlüssel. Wähle einen Anbieter, füge einen Schlüssel ein und wähle ein Modell. Dein Schlüssel wird sicher im macOS-Schlüsselbund gespeichert und verlässt deinen Mac nur als die Anfrage, die du stellst.",
    "Coherence estimate": "Kohärenz-Schätzung",
    "Coming together": "Wird zusammengeführt",
    "Compare": "Vergleichen",
    "Compare needs at least two metrics with history. Import your WHOOP export in Data Sources first.": "Für den Vergleich werden mindestens zwei Metriken mit Verlauf benötigt. Importiere zuerst deinen WHOOP-Export unter Datenquellen.",
    "Complete": "Abgeschlossen",
    "Configure": "Konfigurieren",
    "Connect a provider": "Anbieter verbinden",
    "Connect strap for buzz cues": "Strap für Vibrationshinweise verbinden",
    "Connect your strap for haptic guidance — you'll feel one pulse on the inhale, two on the exhale, so you can breathe with your eyes closed.": "Verbinde deinen Strap für haptische Führung — du spürst einen Impuls beim Einatmen, zwei beim Ausatmen, sodass du mit geschlossenen Augen atmen kannst.",
    "Connect your strap to enable": "Verbinde deinen Strap zum Aktivieren",
    "Connect your strap to test": "Verbinde deinen Strap zum Testen",
    "Connected": "Verbunden",
    "Connecting…": "Verbinde…",
    "Consistency": "Konsistenz",
    "Control Center": "Kontrollzentrum",
    "Copied!": "Kopiert!",
    "Copy": "Kopieren",
    "Copy address": "Adresse kopieren",
    "Crunching your raw streams…": "Deine Rohdaten werden verarbeitet…",
    "Custom model id": "Eigene Modell-ID",
    "Custom…": "Benutzerdefiniert…",
    "Daily signals": "Tägliche Signale",
    "Data Sources": "Datenquellen",
    "Date": "Datum",
    "Day strain": "Tagesbelastung",
    "Day Strain": "Tagesbelastung",
    "Days": "Tage",
    "Deep": "Tief",
    "Depleted": "Erschöpft",
    "Disconnect": "Trennen",
    "Don't see it? That's normal.": "Nicht zu sehen? Das ist normal.",
    "Donation QR code": "Spenden-QR-Code",
    "Effect size": "Effektstärke",
    "Efficiency": "Effizienz",
    "Email": "E-Mail",
    "Enable wrist alerts": "Handgelenk-Hinweise aktivieren",
    "Enter a model id": "Modell-ID eingeben",
    "Estimate only — a higher RMSSD while paced usually means your parasympathetic \"rest\" branch is engaging. It is not a clinical reading; trends over a session matter more than any single number.": "Nur eine Schätzung — ein höherer RMSSD beim getakteten Atmen bedeutet meist, dass dein parasympathischer \"Ruhe\"-Zweig aktiv wird. Es ist kein klinischer Wert; Trends über eine Sitzung sind wichtiger als ein einzelner Wert.",
    "Every beat, every night, every day — woven into one quiet picture of you. Welcome to NOOP.": "Jeder Schlag, jede Nacht, jeder Tag — verwoben zu einem ruhigen Bild von dir. Willkommen bei NOOP.",
    "Every session, threaded together.": "Jede Sitzung, miteinander verwoben.",
    "Every signal, one tap deep.": "Jedes Signal, nur einen Tipp entfernt.",
    "Everything stays on this Mac. Bring your history in once, then it's yours.": "Alles bleibt auf diesem Mac. Importiere deine Historie einmal, dann gehört sie dir.",
    "Experimental · WHOOP 5 / MG": "Experimentell · WHOOP 5 / MG",
    "EXPLORATORY": "EXPLORATIV",
    "Explore": "Entdecken",
    "Export frames…": "Frames exportieren…",
    "Export…": "Exportieren…",
    "Female": "Weiblich",
    "Find it in the sidebar under Data Sources.": "Du findest es in der Seitenleiste unter Datenquellen.",
    "Fire a single haptic pulse on the strap (requires a bonded connection)": "Einen einzelnen haptischen Impuls am Strap auslösen (erfordert eine gekoppelte Verbindung)",
    "Fire a test buzz now": "Jetzt eine Testvibration auslösen",
    "Fire a test haptic buzz on the strap (requires an active strap connection)": "Eine haptische Testvibration am Strap auslösen (erfordert eine aktive Strap-Verbindung)",
    "Fires a test buzz on your strap": "Löst eine Testvibration an deinem Strap aus",
    "Forget the saved key and disconnect": "Gespeicherten Schlüssel vergessen und trennen",
    "From": "Von",
    "Get in touch": "Kontakt aufnehmen",
    "Get the latest release": "Neueste Version laden",
    "Got it": "Verstanden",
    "Haptic-paced breathing · watch your HRV respond": "Haptisch getaktetes Atmen · beobachte, wie deine HRV reagiert",
    "Haptics on": "Haptik an",
    "Health": "Gesundheit",
    "Health Monitor": "Gesundheitsmonitor",
    "Heart & Vitals": "Herz & Vitalwerte",
    "Heart Rate": "Herzfrequenz",
    "HEART RATE": "HERZFREQUENZ",
    "Heart rate variability": "Herzfrequenzvariabilität",
    "Height": "Größe",
    "high": "hoch",
    "History": "Verlauf",
    "History synced %@": "Verlauf synchronisiert %@",
    "Hours asleep": "Schlafstunden",
    "Hours vs Needed": "Stunden vs. Bedarf",
    "How They Move Together": "Wie sie sich gemeinsam bewegen",
    "How this is computed": "Wie das berechnet wird",
    "How this works": "Wie das funktioniert",
    "HR Zones": "HF-Zonen",
    "HRV": "HRV",
    "I keep this project anonymous, so crypto is the only way to chip in — no Patreon, no PayPal, no name attached. Quick, global, and private for both of us.": "Ich halte dieses Projekt anonym, daher ist Krypto die einzige Möglichkeit, beizutragen — kein Patreon, kein PayPal, kein Name. Schnell, weltweit und privat für uns beide.",
    "Import your history first. A WHOOP export in Data Sources fills every metric you can explore here in about a minute.": "Importiere zuerst deine Historie. Ein WHOOP-Export unter Datenquellen füllt in etwa einer Minute jede Metrik, die du hier erkunden kannst.",
    "Import…": "Importieren…",
    "Importing overwrites everything currently on this Mac. Your old data is kept in a side file just in case. NOOP needs a relaunch for an import to take effect.": "Der Import überschreibt alles, was sich derzeit auf diesem Mac befindet. Deine alten Daten werden sicherheitshalber in einer separaten Datei aufbewahrt. NOOP muss neu gestartet werden, damit ein Import wirksam wird.",
    "Importing…": "Importiere…",
    "Insights": "Einblicke",
    "Insights read your journal and outcomes. Import your WHOOP export, which includes your journal, in Data Sources to unlock them.": "Einblicke lesen dein Journal und deine Ergebnisse. Importiere deinen WHOOP-Export, der dein Journal enthält, unter Datenquellen, um sie freizuschalten.",
    "Intelligence": "Intelligenz",
    "Interrogate what affects what.": "Untersuche, was was beeinflusst.",
    "Interval Timer": "Intervall-Timer",
    "Intervals": "Intervalle",
    "Key Metrics": "Kernmetriken",
    "Last night": "Letzte Nacht",
    "Last night, read in two seconds.": "Letzte Nacht, in zwei Sekunden erfasst.",
    "Last Workouts": "Letzte Workouts",
    "Latest": "Aktuellste",
    "Latest reading": "Aktuellster Messwert",
    "Lean body mass": "Magermasse",
    "Lean Mass": "Magermasse",
    "Learning your baseline — %lld of %lld nights.": "Deine Baseline wird gelernt — %lld von %lld Nächten.",
    "Let the coach use my data": "Dem Coach erlauben, meine Daten zu nutzen",
    "Light": "Leicht",
    "Live": "Live",
    "Live heart rate already works on a WHOOP 5/MG strap. These probes go further and try to coax more out of it. They are guesses, off by default, and only ever touch a 5/MG strap — WHOOP 4.0 is never affected.": "Die Live-Herzfrequenz funktioniert bereits an einem WHOOP 5/MG-Strap. Diese Tests gehen weiter und versuchen, mehr herauszuholen. Es sind Vermutungen, standardmäßig deaktiviert, und betreffen nur einen 5/MG-Strap — WHOOP 4.0 ist nie betroffen.",
    "Live now. Your scores are building.": "Jetzt live. Deine Werte werden aufgebaut.",
    "Live vitals, streamed from the strap.": "Live-Vitalwerte, gestreamt vom Strap.",
    "load %@": "Last %@",
    "Loading your history…": "Deine Historie wird geladen…",
    "Loading your sessions…": "Deine Sitzungen werden geladen…",
    "Loading your sleep history…": "Dein Schlafverlauf wird geladen…",
    "Log": "Protokoll",
    "low": "niedrig",
    "Low": "Niedrig",
    "Make the strap do things — tap to act, walk away to lock, train by feel.": "Lass den Strap Dinge tun — tippen zum Auslösen, weggehen zum Sperren, nach Gefühl trainieren.",
    "Male": "Männlich",
    "Manual override": "Manuelle Übersteuerung",
    "Markers": "Marker",
    "Max": "Max",
    "Max 4": "Max. 4",
    "Max heart rate": "Maximale Herzfrequenz",
    "Max heart rate override": "Manuelle maximale Herzfrequenz",
    "Max HR": "Max. HF",
    "Metric": "Metrik",
    "Metric Relationships": "Metrik-Beziehungen",
    "Metrics": "Metriken",
    "mid": "mittel",
    "Min": "Min",
    "Model": "Modell",
    "Most Active": "Aktivste",
    "Move all your NOOP data to another machine. Export saves everything — history, sleeps, workouts, settings — to a single file you can copy across; import replaces this Mac's data with a backup.": "Übertrage alle deine NOOP-Daten auf einen anderen Rechner. Der Export speichert alles — Historie, Schlafphasen, Workouts, Einstellungen — in einer einzelnen Datei, die du kopieren kannst; der Import ersetzt die Daten dieses Macs durch eine Sicherung.",
    "Movement": "Bewegung",
    "n.s.": "n.s.",
    "Night detail": "Nacht-Details",
    "Nights": "Nächte",
    "No biometrics yet. Import your WHOOP export (and Apple Health if you have it) in Data Sources to fill this in.": "Noch keine Biometrie. Importiere deinen WHOOP-Export (und Apple Health, falls vorhanden) unter Datenquellen, um dies zu füllen.",
    "No data": "Keine Daten",
    "NO DATA": "KEINE DATEN",
    "No nights here yet. Import your WHOOP export in Data Sources to see every night, your sleep stages and trends straight away. Or open Intelligence to see last night computed from the strap after you wear it to bed.": "Noch keine Nächte hier. Importiere deinen WHOOP-Export unter Datenquellen, um sofort jede Nacht, deine Schlafphasen und Trends zu sehen. Oder öffne Intelligenz, um die letzte Nacht aus dem Strap berechnet zu sehen, nachdem du ihn nachts getragen hast.",
    "No readings recorded.": "Keine Messwerte aufgezeichnet.",
    "No stress history yet. Import your WHOOP export in Data Sources to see it.": "Noch kein Stressverlauf. Importiere deinen WHOOP-Export unter Datenquellen, um ihn zu sehen.",
    "No workouts yet. They come from your WHOOP and Apple Health history. Import in Data Sources to bring them in.": "Noch keine Workouts. Sie stammen aus deinem WHOOP- und Apple-Health-Verlauf. Importiere sie unter Datenquellen.",
    "Non-binary": "Nichtbinär",
    "NOOP — all your data, none of the cloud.": "NOOP — all deine Daten, nichts in der Cloud.",
    "NOOP is free and always will be, nothing is locked. It cost real money and a lot of unpaid hours to build, and there's a Windows app, an Android app and an iOS app I want to ship next. If it's useful to you and you want to help with the development and testing costs, even a few quid in crypto genuinely keeps it moving, and honestly it keeps me motivated to keep building.": "NOOP ist kostenlos und bleibt es, nichts ist gesperrt. Es hat echtes Geld und viele unbezahlte Stunden gekostet, und es gibt eine Windows-App, eine Android-App und eine iOS-App, die ich als Nächstes veröffentlichen möchte. Wenn es dir nützt und du bei den Entwicklungs- und Testkosten helfen möchtest, hält es schon mit ein paar Euro in Krypto wirklich am Laufen — und ehrlich gesagt motiviert es mich, weiterzubauen.",
    "NOOP is not a medical device. It is for informational and personal-insight purposes only and is not intended to diagnose, treat, cure or prevent any condition. Talk to a clinician for medical advice.": "NOOP ist kein medizinisches Gerät. Es dient nur zu Informations- und persönlichen Erkenntniszwecken und ist nicht dazu bestimmt, Erkrankungen zu diagnostizieren, zu behandeln, zu heilen oder zu verhindern. Wende dich für medizinischen Rat an eine Fachperson.",
    "NOOP pairs directly with your WHOOP over Bluetooth — no WHOOP app, no cloud.": "NOOP koppelt sich direkt über Bluetooth mit deinem WHOOP — keine WHOOP-App, keine Cloud.",
    "NOOP scores your recovery, strain and sleep itself — on-device, no cloud.": "NOOP berechnet deine Erholung, Belastung und deinen Schlaf selbst — auf dem Gerät, ohne Cloud.",
    "NOOP-computed": "Von NOOP berechnet",
    "Normalized": "Normalisiert",
    "Normalized overlay": "Normalisierte Überlagerung",
    "Not affiliated with, endorsed by, or connected to WHOOP. Interoperability software for hardware you own and your own data. Use it only with a device you own, and not in breach of any agreement that applies to you. Not a medical device.": "Nicht mit WHOOP verbunden, von WHOOP unterstützt oder zu WHOOP gehörend. Interoperabilitätssoftware für Hardware, die dir gehört, und deine eigenen Daten. Nutze sie nur mit einem Gerät, das dir gehört, und nicht unter Verletzung einer für dich geltenden Vereinbarung. Kein medizinisches Gerät.",
    "Not enough data for this window.": "Nicht genug Daten für diesen Zeitraum.",
    "Not enough nights yet.": "Noch nicht genug Nächte.",
    "Not enough overlapping history to correlate your metrics yet.": "Noch nicht genug überlappender Verlauf, um deine Metriken zu korrelieren.",
    "Not enough recent days to chart a trend yet. Import a history or keep wearing your strap.": "Noch nicht genug aktuelle Tage, um einen Trend darzustellen. Importiere eine Historie oder trage deinen Strap weiter.",
    "Not synced yet": "Noch nicht synchronisiert",
    "Nothing imported yet. On an iPhone: Health app, tap your photo, Export All Health Data, then import the .zip here in Data Sources.": "Noch nichts importiert. Auf einem iPhone: Health-App, tippe auf dein Foto, „Alle Gesundheitsdaten exportieren“, dann importiere die .zip hier unter Datenquellen.",
    "Nothing selected yet.": "Noch nichts ausgewählt.",
    "Notifications": "Mitteilungen",
    "Off": "Aus",
    "Off — the coach answers generally and sends none of your metrics.": "Aus — der Coach antwortet allgemein und sendet keine deiner Metriken.",
    "OK": "OK",
    "On — your recovery, sleep, HRV and workouts are shared with the provider for tailored coaching.": "An — deine Erholung, dein Schlaf, deine HRV und Workouts werden für maßgeschneidertes Coaching mit dem Anbieter geteilt.",
    "On a 5/MG connection NOOP will send a puffin realtime-stream request after the handshake, and log what comes back. If you have a 5/MG strap, turning this on and sharing your strap log helps map the protocol. No effect on WHOOP 4.0.": "Bei einer 5/MG-Verbindung sendet NOOP nach dem Handshake eine Puffin-Echtzeitstream-Anfrage und protokolliert die Antwort. Wenn du einen 5/MG-Strap hast, hilft das Aktivieren und Teilen deines Strap-Protokolls, das Protokoll zu kartieren. Keine Auswirkung auf WHOOP 4.0.",
    "Open-source BLE reverse-engineering work. Thank you.": "Open-Source-BLE-Reverse-Engineering-Arbeit. Danke.",
    "Opens the GitHub releases page in your browser. NOOP itself makes no network connections — the macOS sandbox has no network entitlement.": "Öffnet die GitHub-Releases-Seite in deinem Browser. NOOP selbst stellt keine Netzwerkverbindungen her — die macOS-Sandbox hat keine Netzwerk-Berechtigung.",
    "Outcome metric": "Ergebnismetrik",
    "Overlay": "Überlagerung",
    "Overlay 2–4 signals": "2–4 Signale überlagern",
    "Overlay signals, draw conclusions.": "Signale überlagern, Schlüsse ziehen.",
    "p < 0.05": "p < 0,05",
    "Pause": "Pause",
    "Paused": "Pausiert",
    "Peak": "Spitze",
    "Peaked": "Höchststand",
    "Pearson r": "Pearson r",
    "Pearson r over the visible window · |r| ≥ 0.30, n ≥ 10": "Pearson r über den sichtbaren Bereich · |r| ≥ 0,30, n ≥ 10",
    "Points": "Punkte",
    "Profile": "Profil",
    "Provenance": "Herkunft",
    "Provider": "Anbieter",
    "Question": "Frage",
    "Quiet hours end": "Ende der Ruhezeit",
    "Quiet hours start": "Beginn der Ruhezeit",
    "Re-scan": "Erneut suchen",
    "Readiness": "Bereitschaft",
    "Reading your Apple Health history…": "Dein Apple-Health-Verlauf wird gelesen…",
    "Reading your heart-rate variability and resting heart rate…": "Deine Herzfrequenzvariabilität und Ruheherzfrequenz werden gelesen…",
    "Reading your history…": "Deine Historie wird gelesen…",
    "Reading your journal and outcomes…": "Dein Journal und deine Ergebnisse werden gelesen…",
    "Ready": "Bereit",
    "Ready to scan": "Bereit zum Suchen",
    "Recent moments": "Aktuelle Momente",
    "Recompute": "Neu berechnen",
    "Record puffin frames to a file": "Puffin-Frames in eine Datei aufzeichnen",
    "Recovery": "Erholung",
    # Coupled view dashboard card (task #43) — was absent from the catalog, so it shipped in English
    # on non-English devices (#484). Re-uses the catalog's own Erholung / Anstrengung / Schlaf terms.
    "Coupled view": "Zusammengefasste Ansicht",
    "Recovery, strain and sleep in one glance": "Erholung, Anstrengung und Schlaf auf einen Blick",
    "Recovery weighs your HRV against your personal baseline (~60%), resting heart rate (~20%), sleep performance (~15%) and respiration (~5%). Day strain is a 0–21 cardiovascular load from time in heart-rate zones. Sleep is staged from movement and heart rate. Everything is computed here from the strap's raw data — it works for any day NOOP collected raw streams.": "Die Erholung gewichtet deine HRV gegenüber deiner persönlichen Basislinie (~60 %), die Ruheherzfrequenz (~20 %), die Schlafleistung (~15 %) und die Atmung (~5 %). Die Tagesbelastung ist eine kardiovaskuläre Last von 0–21 aus der Zeit in Herzfrequenzzonen. Der Schlaf wird aus Bewegung und Herzfrequenz in Phasen eingeteilt. Alles wird hier aus den Rohdaten des Straps berechnet — es funktioniert für jeden Tag, an dem NOOP Rohdaten erfasst hat.",
    "Refresh models": "Modelle aktualisieren",
    "Refresh models from provider": "Modelle vom Anbieter aktualisieren",
    "REM": "REM",
    "Reset": "Zurücksetzen",
    "Reset API key": "API-Schlüssel zurücksetzen",
    "Reset key": "Schlüssel zurücksetzen",
    "Respiratory": "Atmung",
    "Respiratory rate": "Atemfrequenz",
    "Rest": "Ruhe",
    "Restart": "Neu starten",
    "Resting heart rate": "Ruheherzfrequenz",
    "Resting HR": "Ruhe-HF",
    "Restorative": "Erholsam",
    "Reveal in Finder": "Im Finder anzeigen",
    "ROUND": "RUNDE",
    "Running": "Läuft",
    "Save key": "Schlüssel speichern",
    "Save…": "Speichern…",
    "Saves every raw 5/MG frame (with a timestamp and the live heart rate) to a JSON file you can share to help map the biometric layout. This only records frames the strap already sent — it never writes to your strap — so it is safe to leave on. Export the file and attach it to a protocol-mapping issue.": "Speichert jeden rohen 5/MG-Frame (mit Zeitstempel und Live-Herzfrequenz) in einer JSON-Datei, die du teilen kannst, um das biometrische Layout zu kartieren. Dies zeichnet nur Frames auf, die der Strap bereits gesendet hat — es schreibt nie auf deinen Strap — daher ist es sicher, es aktiviert zu lassen. Exportiere die Datei und hänge sie an ein Protokoll-Mapping-Issue an.",
    "Scan": "Suchen",
    "Scan & Connect": "Suchen & Verbinden",
    "Scanning…": "Suche…",
    "Searching": "Suche",
    "SECONDS": "SEKUNDEN",
    "Send": "Senden",
    "Session": "Sitzung",
    "SESSION DONE": "SITZUNG FERTIG",
    "Session live": "Sitzung live",
    "Settings": "Einstellungen",
    "Sex": "Geschlecht",
    "Share of imported zone time, duration-weighted across sessions — approximate.": "Anteil der importierten Zonenzeit, zeitgewichtet über alle Einheiten — Näherungswert.",
    "Should you push today?": "Solltest du heute Gas geben?",
    "SIGNIFICANT": "SIGNIFIKANT",
    "Silent haptic HIIT — the strap buzzes the transitions": "Stilles haptisches HIIT — der Strap vibriert die Übergänge",
    "Skip for now": "Vorerst überspringen",
    "Sleep": "Schlaf",
    "Sleep Debt": "Schlafdefizit",
    "Sleep Performance": "Schlafleistung",
    "Slow threads": "Langsame Verläufe",
    "Source Apple Health": "Quelle Apple Health",
    "Source Whoop": "Quelle Whoop",
    "Stage breakdown": "Phasen-Aufschlüsselung",
    "Stages vs typical": "Phasen vs. typisch",
    "Start": "Start",
    "Start session": "Sitzung starten",
    "State": "Zustand",
    "Steps": "Schritte",
    "Stop session": "Sitzung beenden",
    "Strap": "Strap",
    "Strap bonded": "Strap gekoppelt",
    "STRAP LOG": "STRAP-PROTOKOLL",
    "Strap not connected": "Strap nicht verbunden",
    "Strap sync": "Strap-Sync",
    "Stress": "Stress",
    "Stress · M": "Stress · M",
    "Stress is derived from two autonomic signals.": "Stress wird aus zwei autonomen Signalen abgeleitet.",
    "Stress monitor": "Stress-Monitor",
    "Stress Trend": "Stress-Trend",
    "Support": "Support",
    "Support NOOP — donate or get in touch": "NOOP unterstützen — spenden oder Kontakt aufnehmen",
    "Support the build": "Die Entwicklung unterstützen",
    "Syncing strap history…": "Strap-Verlauf wird synchronisiert…",
    "Test action": "Aktion testen",
    "Test buzz": "Testvibration",
    "The thread of you over time.": "Dein Verlauf über die Zeit.",
    "These power your heart-rate zones, calorie estimates and recovery baselines. Keep them accurate.": "Diese steuern deine Herzfrequenzzonen, Kalorienschätzungen und Erholungs-Basislinien. Halte sie genau.",
    "Thinking": "Denkt nach",
    "This builds from the strap as it syncs. Strain and sleep appear after you have worn it and slept a night. Recovery needs about a week of nights to learn your baseline, or import your WHOOP export to skip the wait.": "Dies baut sich aus dem Strap auf, während er synchronisiert. Belastung und Schlaf erscheinen, nachdem du ihn getragen und eine Nacht geschlafen hast. Die Erholung braucht etwa eine Woche an Nächten, um deine Basislinie zu lernen, oder importiere deinen WHOOP-Export, um die Wartezeit zu überspringen.",
    "This stands on community reverse-engineering. Huge thanks:": "Dies basiert auf Reverse-Engineering der Community. Großen Dank:",
    "Time range": "Zeitbereich",
    "to": "bis",
    "Today": "Heute",
    "Today’s Synthesis": "Heutige Zusammenfassung",
    "Today's value is your recorded daily stress score (0–3).": "Der heutige Wert ist dein aufgezeichneter täglicher Stresswert (0–3).",
    "Total Calories": "Kalorien gesamt",
    "Total Distance": "Distanz gesamt",
    "Total Time": "Zeit gesamt",
    "Total Workouts": "Workouts gesamt",
    "Trend": "Trend",
    "Trends": "Trends",
    "Trends need history to draw. Import your WHOOP export in Data Sources to see weeks, months and years instantly.": "Trends benötigen Verlauf zur Darstellung. Importiere deinen WHOOP-Export unter Datenquellen, um Wochen, Monate und Jahre sofort zu sehen.",
    "Try again": "Erneut versuchen",
    "Try WHOOP 5/MG protocol probes": "WHOOP 5/MG-Protokolltests ausprobieren",
    "Use": "Verwenden",
    "Use custom model": "Eigenes Modell verwenden",
    "Visual only": "Nur visuell",
    "Vital Signs": "Vitalwerte",
    "VO₂ Max": "VO₂max",
    "Wake at": "Aufwachen um",
    "We compare today's resting heart rate and HRV to your own 30-day baseline. A higher-than-usual resting HR and a lower-than-usual HRV both push the score up — classic signs the body is activated. The combined shift is mapped onto a 0–3 scale: 0 is calm, 1.5 sits at your baseline, 3 is highly activated.": "Wir vergleichen die heutige Ruheherzfrequenz und HRV mit deiner eigenen 30-Tage-Basislinie. Eine höhere Ruhe-HF als üblich und eine niedrigere HRV als üblich treiben den Wert beide nach oben — klassische Zeichen dafür, dass der Körper aktiviert ist. Die kombinierte Verschiebung wird auf eine Skala von 0–3 abgebildet: 0 ist ruhig, 1,5 liegt auf deiner Basislinie, 3 ist hoch aktiviert.",
    "Weight": "Gewicht",
    "What correlates": "Was korreliert",
    "WHAT TO EXPECT": "WAS DICH ERWARTET",
    "What's new": "Was ist neu",
    "When I double-tap": "Wenn ich doppelt tippe",
    "When the system prompt appears, choose Allow so NOOP can find your strap.": "Wenn die Systemabfrage erscheint, wähle „Erlauben“, damit NOOP deinen Strap finden kann.",
    "Which strap?": "Welcher Strap?",
    "Whoop": "Whoop",
    "Whoop import": "Whoop-Import",
    "WHOOP straps don't appear in macOS System Settings → Bluetooth. They advertise on a custom profile that only apps like NOOP can find — so there's nothing to pair there, and you shouldn't try.": "WHOOP-Straps erscheinen nicht in den macOS-Systemeinstellungen → Bluetooth. Sie senden über ein eigenes Profil, das nur Apps wie NOOP finden können — dort gibt es also nichts zu koppeln, und du solltest es nicht versuchen.",
    "Window": "Fenster",
    "With": "Mit",
    "Without": "Ohne",
    "Working…": "Arbeite…",
    "Workouts": "Workouts",
    "Wrist delivery isn't live yet — it needs a small on-device watcher (coming in an update) to read macOS notifications. Everything stays on this Mac. Your choices are saved now and will apply automatically once delivery ships.": "Die Zustellung ans Handgelenk ist noch nicht aktiv — sie benötigt einen kleinen Dienst auf dem Gerät (kommt in einem Update), um macOS-Mitteilungen zu lesen. Alles bleibt auf diesem Mac. Deine Auswahl ist jetzt gespeichert und wird automatisch angewendet, sobald die Zustellung verfügbar ist.",
    "You're connected.": "Du bist verbunden.",
    "Your live heart rate is working from the strap, and recovery, strain and sleep build from it over your next few nights of wear, sharpening as it learns your baseline. Want your full history instantly? Import your WHOOP export in Data Sources and it backfills in about a minute.": "Deine Live-Herzfrequenz funktioniert über den Strap, und Erholung, Belastung und Schlaf bauen sich daraus über deine nächsten Nächte des Tragens auf und werden schärfer, während er deine Basislinie lernt. Willst du sofort deine vollständige Historie? Importiere deinen WHOOP-Export unter Datenquellen, und er wird in etwa einer Minute nachgefüllt.",
    "Your numbers, your strap, and how NOOP works. All on this Mac.": "Deine Werte, dein Strap und wie NOOP funktioniert. Alles auf diesem Mac.",
    "Your strap in real time — heart rate and frames as they arrive.": "Dein Strap in Echtzeit — Herzfrequenz und Frames, sobald sie eintreffen.",
    "Your thread starts here.": "Dein Verlauf beginnt hier.",
    "Zone": "Zone",
}


def main() -> int:
    # encoding="utf-8" is load-bearing: without it Windows defaults to cp1252 and a run
    # mojibakes every umlaut in the catalog (empirically: 82 German strings corrupted).
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = catalog["strings"]

    missing: list[str] = []
    for key, entry in strings.items():
        if not key:
            continue
        de = DE.get(key)
        if de is None:
            missing.append(key)
            continue
        locs = entry.setdefault("localizations", {})
        locs["de"] = {"stringUnit": {"state": "translated", "value": de}}

    CATALOG.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")

    translated = sum(
        1 for k, v in strings.items()
        if k and "de" in v.get("localizations", {})
    )
    print(f"German units written: {translated}")
    if missing:
        print(f"MISSING ({len(missing)}):")
        for k in missing:
            print("  " + repr(k))
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
