#!/usr/bin/env python3
"""Inject Italian (it) translations into Strand/Resources/Localizable.xcstrings.

Mirrors the other translate-*.py tools: it reads the English (en) base keys and
writes an `it` stringUnit for each one. Format placeholders and the brand names
NOOP / WHOOP are preserved verbatim. Re-runnable: any existing `it` unit is
overwritten, so this script stays the source of truth for the Italian copy.
House style across the catalog has no em-dash (U+2014); the table below follows
that, using a comma where English pauses.
"""
import json
from pathlib import Path

CATALOG = Path("Strand/Resources/Localizable.xcstrings")

# English key -> Italian value. Keys match the catalog exactly.
IT: dict[str, str] = {
    '—': '—',
    '·': '·',
    '· %@': '· %@',
    '/ %lld': '/ %lld',
    '% Max': '% Max',
    '%@': '%@',
    '%@ – %@': '%@ – %@',
    '%@ · %@': '%@ · %@',
    '%@ · n = %lld': '%@ · n = %lld',
    '%@ / %@': '%@ / %@',
    '%@ %@': '%@ %@',
    '%@ ↔ %@': '%@ ↔ %@',
    "%@ is free and always will be. If it's useful to you, you can chip in to help with development and testing costs. Totally optional.": '%@ è gratuito e lo sarà sempre. Se ti è utile, puoi contribuire ai costi di sviluppo e test. Del tutto facoltativo.',
    '%@ versus %@, r equals %@, %lld days': '%@ contro %@, r uguale a %@, %lld giorni',
    '%@ wrist alerts': '%@ avvisi al polso',
    '%@, %@%@': '%@, %@%@',
    '%@, correlation %@, %lld days': '%@, correlazione %@, %lld giorni',
    '%@, range %@ to %@': '%@, intervallo da %@ a %@',
    '%@: %@ last night%@': '%@: %@ la scorsa notte%@',
    '%@%@': '%@%@',
    '%lld': '%lld',
    '%lld / %lld': '%lld / %lld',
    '%lld app%@ on': '%lld app%@ attive',
    '%lld breaths': '%lld respiri',
    '%lld days · %lld sleeps stored': '%lld giorni · %lld sonni memorizzati',
    '%lld frame%@ captured this session.': '%lld frame%@ acquisiti in questa sessione.',
    '%lld min': '%lld min',
    '%lld of %lld nights': '%lld di %lld notti',
    '%lld overlapping days · %@ %@ correlation': '%lld giorni sovrapposti · correlazione %@ %@',
    '%lld–%lld%@ · step %lld': '%lld–%lld%@ · passo %lld',
    '•': '•',
    '✓': '✓',
    'A private window into your recovery, sleep and strain , read straight from your strap, kept only on this Mac.': 'Una finestra privata sul tuo recupero, sonno e carico, letti direttamente dalla tua fascia, conservati solo su questo Mac.',
    'A standalone companion for your WHOOP. Everything stays on this device , your history, your live stream, your numbers. Nothing is uploaded. NOOP is an independent, experimental project, not the WHOOP app.': "Un'app companion autonoma per il tuo WHOOP. Tutto resta su questo dispositivo, la tua cronologia, il tuo flusso in diretta, i tuoi numeri. Nulla viene caricato online. NOOP è un progetto indipendente e sperimentale, non è l'app WHOOP.",
    'About': 'Informazioni',
    'Active energy': 'Energia attiva',
    'Activity': 'Attività',
    'Activity & Energy': 'Attività ed energia',
    'Activity Breakdown': 'Dettaglio attività',
    'Acute (7-day) vs chronic (28-day) training load. 0.8–1.3 is the sweet spot.': 'Carico di allenamento acuto (7 giorni) rispetto a cronico (28 giorni). 0,8–1,3 è la fascia ideale.',
    'Add a metric to compare': 'Aggiungi una metrica da confrontare',
    'Add metric': 'Aggiungi metrica',
    'Age': 'Età',
    'Age, %lld years': 'Età, %lld anni',
    'All Sessions': 'Tutte le sessioni',
    'ALL YOUR DATA · NONE OF THE CLOUD': 'TUTTI I TUOI DATI · NIENTE CLOUD',
    'all your data, none of the cloud': 'tutti i tuoi dati, niente cloud',
    'Any amount helps. Thank you , genuinely.': "Qualsiasi importo è d'aiuto. Grazie, davvero.",
    'API key': 'Chiave API',
    'Apple': 'Apple',
    'Apple Health': 'Apple Health',
    'Ask about your recovery, strain, sleep and workouts , grounded in your own numbers.': 'Fai domande su recupero, carico, sonno e allenamenti, basate sui tuoi numeri.',
    'Ask Coach about your data…': 'Chiedi al Coach informazioni sui tuoi dati…',
    'Ask your first question': 'Fai la tua prima domanda',
    'Asleep': 'Addormentato',
    'Asleep avg': 'Media addormentato',
    'Asleep duration': 'Durata del sonno',
    'At a glance': 'In sintesi',
    'Auto': 'Auto',
    'Auto · %lld bpm (Tanaka)': 'Auto · %lld bpm (Tanaka)',
    'Automations': 'Automazioni',
    'Autonomic load from HRV and resting heart rate': 'Carico autonomico da HRV e frequenza cardiaca a riposo',
    'Average': 'Media',
    'Avg': 'Media',
    'Awake': 'Sveglio',
    'Back': 'Indietro',
    'Backup & restore': 'Backup e ripristino',
    'Battery %lld%%': 'Batteria %lld%%',
    'Battery %lld%% · Charging': 'Batteria %lld%% · In carica',
    'Behaviour Effects': 'Effetti dei comportamenti',
    'Blood oxygen': 'Ossigeno nel sangue',
    'Blood Oxygen': 'Ossigeno nel sangue',
    'BMI': 'BMI',
    'Body Composition': 'Composizione corporea',
    'Body fat': 'Grasso corporeo',
    'Body Fat': 'Grasso corporeo',
    'Bond your strap on the Live screen to feel the transitions hands-free.': 'Abbina la tua fascia nella schermata In diretta per sentire le transizioni a mani libere.',
    'bpm': 'bpm',
    'BPM': 'BPM',
    'Breathe': 'Respira',
    'Building from your strap': 'Creazione in corso dalla fascia',
    'Built on': 'Basato su',
    'Buzz cues on': 'Segnali vibrazione attivi',
    'Buzz strap': 'Fai vibrare la fascia',
    'Buzz your strap when these apps notify you. Everything runs on this Mac.': 'Fai vibrare la tua fascia quando queste app ti inviano notifiche. Tutto avviene su questo Mac.',
    'Buzzes your wrist': 'Fa vibrare il tuo polso',
    'By sport': 'Per sport',
    'Calendar': 'Calendario',
    'Calibrating': 'Calibrazione',
    'Calm time': 'Tempo di calma',
    'Calories': 'Calorie',
    'Cardiac': 'Cardiaco',
    'Category': 'Categoria',
    'Choose export…': "Scegli l'esportazione…",
    'Choose export.zip…': 'Scegli export.zip…',
    'Choose the buzz pattern for %@': 'Scegli il motivo di vibrazione per %@',
    'Clear': 'Cancella',
    'Close': 'Chiudi',
    'Close Support': 'Chiudi Supporto',
    'Coach': 'Coach',
    'Coach is thinking': 'Il Coach sta pensando',
    'Coach is thinking…': 'Il Coach sta pensando…',
    'Coach reads a summary of your last two weeks plus 30-day averages and recent workouts, then answers in plain language. Try a suggestion below.': 'Il Coach legge un riepilogo delle tue ultime due settimane più le medie su 30 giorni e gli allenamenti recenti, poi risponde in linguaggio naturale. Prova un suggerimento qui sotto.',
    'Coach said: %@': 'Il Coach ha detto: %@',
    'Coach uses your own API key. Pick a provider, paste a key, and choose a model. Your key is stored securely in the macOS Keychain and never leaves your Mac except as the request you make.': 'Il Coach usa la tua chiave API. Scegli un provider, incolla una chiave e seleziona un modello. La tua chiave è conservata in modo sicuro nel Portachiavi di macOS e non lascia mai il tuo Mac, se non come parte della richiesta che effettui.',
    'Coherence estimate': 'Stima di coerenza',
    'Coming together': 'Si sta componendo',
    'Compare': 'Confronta',
    'Compare needs at least two metrics with history. Import your WHOOP export in Data Sources first.': 'Il confronto richiede almeno due metriche con cronologia. Importa prima la tua esportazione WHOOP in Sorgenti dati.',
    'Complete': 'Completo',
    'Configure': 'Configura',
    'Connect a provider': 'Collega un provider',
    'Connect strap for buzz cues': 'Collega la fascia per i segnali di vibrazione',
    "Connect your strap for haptic guidance , you'll feel one pulse on the inhale, two on the exhale, so you can breathe with your eyes closed.": "Collega la tua fascia per la guida aptica, sentirai un impulso durante l'inspirazione e due durante l'espirazione, così puoi respirare a occhi chiusi.",
    'Connect your strap to enable': 'Collega la tua fascia per abilitare',
    'Connect your strap to test': 'Collega la tua fascia per provare',
    'Connected': 'Collegata',
    'Connecting…': 'Collegamento…',
    'Consistency': 'Costanza',
    'Control Center': 'Centro di Controllo',
    'Copied!': 'Copiato!',
    'Copy': 'Copia',
    'Copy %@ address': 'Copia indirizzo %@',
    'Copy address': 'Copia indirizzo',
    'Crunching your raw streams…': 'Elaborazione dei tuoi flussi grezzi…',
    'Custom model id': 'ID modello personalizzato',
    'Custom…': 'Personalizzato…',
    'Daily signals': 'Segnali giornalieri',
    'Data Sources': 'Sorgenti dati',
    'Date': 'Data',
    'Day strain': 'Carico giornaliero',
    'Day Strain': 'Carico giornaliero',
    'Days': 'Giorni',
    'Deep': 'Profondo',
    'Depleted': 'Esaurito',
    'Disconnect': 'Disconnetti',
    "Don't see it? That's normal.": 'Non la vedi? È normale.',
    'Donation QR code': 'Codice QR per donazione',
    'Effect size': "Dimensione dell'effetto",
    'Efficiency': 'Efficienza',
    'Email': 'Email',
    'Email %@': 'Email %@',
    'Enable wrist alerts': 'Abilita avvisi al polso',
    'Enter a model id': 'Inserisci un ID modello',
    'Error: %@': 'Errore: %@',
    'Estimate only , a higher RMSSD while paced usually means your parasympathetic "rest" branch is engaging. It is not a clinical reading; trends over a session matter more than any single number.': 'Solo una stima, un RMSSD più alto durante la respirazione guidata di solito significa che il ramo parasimpatico del "riposo" si sta attivando. Non è una lettura clinica; gli andamenti nel corso di una sessione contano più di qualsiasi singolo numero.',
    'Estimated max heart rate · %lld bpm': 'Frequenza cardiaca massima stimata · %lld bpm',
    'Every beat, every night, every day , woven into one quiet picture of you. Welcome to NOOP.': 'Ogni battito, ogni notte, ogni giorno, intrecciati in un quadro silenzioso di te. Benvenuto in NOOP.',
    'Every session, threaded together.': 'Ogni sessione, intrecciata insieme.',
    'Every signal, one tap deep.': 'Ogni segnale, a un tocco di distanza.',
    "Everything stays on this Mac. Bring your history in once, then it's yours.": 'Tutto resta su questo Mac. Importa la tua cronologia una volta, poi è tua.',
    'Experimental · WHOOP 5 / MG': 'Sperimentale · WHOOP 5 / MG',
    'EXPLORATORY': 'ESPLORATIVO',
    'Explore': 'Esplora',
    'Export frames…': 'Esporta frame…',
    'Export…': 'Esporta…',
    'Female': 'Donna',
    'Fetch the available models from %@ using your saved key': 'Recupera i modelli disponibili da %@ usando la tua chiave salvata',
    'Find it in the sidebar under Data Sources.': 'Lo trovi nella barra laterale sotto Sorgenti dati.',
    'Fire a single haptic pulse on the strap (requires a bonded connection)': 'Invia un singolo impulso aptico alla fascia (richiede una connessione abbinata)',
    'Fire a test buzz now': 'Invia ora una vibrazione di prova',
    'Fire a test haptic buzz on the strap (requires an active strap connection)': 'Invia una vibrazione aptica di prova alla fascia (richiede una connessione attiva con la fascia)',
    'Fires a test buzz on your strap': 'Invia una vibrazione di prova alla tua fascia',
    'Forget the saved key and disconnect': 'Dimentica la chiave salvata e disconnetti',
    'From': 'Da',
    'Get in touch': 'Mettiti in contatto',
    'Get the latest release': "Scarica l'ultima versione",
    'Got it': 'Capito',
    'Haptic-paced breathing · watch your HRV respond': 'Respirazione guidata da vibrazioni · osserva la risposta del tuo HRV',
    'Haptics on': 'Vibrazioni attive',
    'Health': 'Salute',
    'Health Monitor': 'Monitor salute',
    'Heart & Vitals': 'Cuore e parametri vitali',
    'Heart Rate': 'Frequenza cardiaca',
    'HEART RATE': 'FREQUENZA CARDIACA',
    'Heart rate %lld beats per minute': 'Frequenza cardiaca %lld battiti al minuto',
    'Heart rate variability': 'Variabilità della frequenza cardiaca',
    'Height': 'Altezza',
    'high': 'alta',
    'History': 'Cronologia',
    'History synced %@': 'Cronologia sincronizzata %@',
    'Hours asleep': 'Ore di sonno',
    'Hours vs Needed': 'Ore vs necessarie',
    'How They Move Together': 'Come si muovono insieme',
    'How this is computed': 'Come viene calcolato',
    'How this works': 'Come funziona',
    'HR Zones': 'Zone FC',
    'HRV': 'HRV',
    'I keep this project anonymous, so crypto is the only way to chip in , no Patreon, no PayPal, no name attached. Quick, global, and private for both of us.': "Mantengo questo progetto anonimo, quindi le cripto sono l'unico modo per contribuire, niente Patreon, niente PayPal, nessun nome collegato. Veloce, globale e privato per entrambi.",
    'Import your history first. A WHOOP export in Data Sources fills every metric you can explore here in about a minute.': "Importa prima la tua cronologia. Un'esportazione WHOOP in Sorgenti dati riempie in circa un minuto ogni metrica che puoi esplorare qui.",
    'Import…': 'Importa…',
    'Importing overwrites everything currently on this Mac. Your old data is kept in a side file just in case. NOOP needs a relaunch for an import to take effect.': "L'importazione sovrascrive tutto ciò che è attualmente su questo Mac. I tuoi vecchi dati vengono conservati in un file a parte per sicurezza. NOOP deve essere riavviato perché l'importazione abbia effetto.",
    'Importing…': 'Importazione…',
    'Insights': 'Approfondimenti',
    'Insights read your journal and outcomes. Import your WHOOP export, which includes your journal, in Data Sources to unlock them.': 'Gli Approfondimenti leggono il tuo diario e i risultati. Importa la tua esportazione WHOOP, che include il tuo diario, in Sorgenti dati per sbloccarli.',
    'Intelligence': 'Intelligenza',
    'Interrogate what affects what.': 'Indaga cosa influenza cosa.',
    'Interval Timer': 'Timer a intervalli',
    'Intervals': 'Intervalli',
    'Key Metrics': 'Metriche chiave',
    'Last night': 'La scorsa notte',
    'Last night, read in two seconds.': 'La scorsa notte, in due secondi.',
    'Last Workouts': 'Ultimi allenamenti',
    'Latest': 'Più recente',
    'Latest reading': 'Ultima lettura',
    'Lean body mass': 'Massa magra',
    'Lean Mass': 'Massa magra',
    'Learning your baseline , %lld of %lld nights.': 'Apprendimento della tua linea di base, %lld di %lld notti.',
    'Let the coach use my data': 'Consenti al Coach di usare i miei dati',
    'Light': 'Leggero',
    'Live': 'In diretta',
    'Live heart rate already works on a WHOOP 5/MG strap. These probes go further and try to coax more out of it. They are guesses, off by default, and only ever touch a 5/MG strap , WHOOP 4.0 is never affected.': 'La frequenza cardiaca in diretta funziona già su una fascia WHOOP 5/MG. Queste sonde vanno oltre e cercano di ottenere di più. Sono ipotesi, disattivate per impostazione predefinita, e interessano solo una fascia 5/MG, la WHOOP 4.0 non viene mai toccata.',
    'Live now. Your scores are building.': 'Ora in diretta. I tuoi punteggi si stanno costruendo.',
    'Live vitals, streamed from the strap.': 'Parametri vitali in diretta, trasmessi dalla fascia.',
    'load %@': 'carico %@',
    'Loading your history…': 'Caricamento della tua cronologia…',
    'Loading your sessions…': 'Caricamento delle tue sessioni…',
    'Loading your sleep history…': 'Caricamento della cronologia del tuo sonno…',
    'Log': 'Registro',
    'low': 'bassa',
    'Low': 'Bassa',
    'Make the strap do things , tap to act, walk away to lock, train by feel.': 'Fai fare cose alla fascia, tocca per agire, allontanati per bloccare, allenati a sensazione.',
    'Male': 'Uomo',
    'Manual override': 'Override manuale',
    'Markers': 'Indicatori',
    'Max': 'Max',
    'Max 4': 'Max 4',
    'Max heart rate': 'Frequenza cardiaca massima',
    'Max heart rate override': 'Override frequenza cardiaca massima',
    'Max heart rate override, %@': 'Override frequenza cardiaca massima, %@',
    'Max HR': 'FC max',
    'Mean %@': 'Media %@',
    'Metric': 'Metrica',
    'Metric Relationships': 'Relazioni tra metriche',
    'Metrics': 'Metriche',
    'mid': 'media',
    'Min': 'Min',
    'Model': 'Modello',
    'Most Active': 'Più attivo',
    "Move all your NOOP data to another machine. Export saves everything , history, sleeps, workouts, settings , to a single file you can copy across; import replaces this Mac's data with a backup.": "Sposta tutti i tuoi dati NOOP su un altro computer. L'esportazione salva tutto, cronologia, sonni, allenamenti, impostazioni, in un unico file che puoi copiare; l'importazione sostituisce i dati di questo Mac con un backup.",
    'Movement': 'Movimento',
    'n.s.': 'n.s.',
    'Night detail': 'Dettaglio notte',
    'Nights': 'Notti',
    'No biometrics yet. Import your WHOOP export (and Apple Health if you have it) in Data Sources to fill this in.': "Ancora nessun dato biometrico. Importa la tua esportazione WHOOP (e Apple Health se ce l'hai) in Sorgenti dati per popolare questa sezione.",
    'No data': 'Nessun dato',
    'NO DATA': 'NESSUN DATO',
    "No data for these metrics in %@. Widen the range or pick metrics you've logged.": "Nessun dato per queste metriche in %@. Amplia l'intervallo o scegli metriche che hai registrato.",
    'No nights here yet. Import your WHOOP export in Data Sources to see every night, your sleep stages and trends straight away. Or open Intelligence to see last night computed from the strap after you wear it to bed.': 'Ancora nessuna notte qui. Importa la tua esportazione WHOOP in Sorgenti dati per vedere subito ogni notte, le fasi del sonno e gli andamenti. Oppure apri Intelligenza per vedere la scorsa notte calcolata dalla fascia dopo averla indossata a letto.',
    'No readings recorded.': 'Nessuna lettura registrata.',
    'No stress history yet. Import your WHOOP export in Data Sources to see it.': 'Ancora nessuna cronologia dello stress. Importa la tua esportazione WHOOP in Sorgenti dati per vederla.',
    'No workouts yet. They come from your WHOOP and Apple Health history. Import in Data Sources to bring them in.': 'Ancora nessun allenamento. Provengono dalla cronologia del tuo WHOOP e di Apple Health. Importa in Sorgenti dati per aggiungerli.',
    'Non-binary': 'Non binario',
    'NOOP': 'NOOP',
    'NOOP , all your data, none of the cloud.': 'NOOP, tutti i tuoi dati, niente cloud.',
    'NOOP %@': 'NOOP %@',
    "NOOP is free and always will be, nothing is locked. It cost real money and a lot of unpaid hours to build, and there's a Windows app, an Android app and an iOS app I want to ship next. If it's useful to you and you want to help with the development and testing costs, even a few quid in crypto genuinely keeps it moving, and honestly it keeps me motivated to keep building.": "NOOP è gratuito e lo sarà sempre, nulla è bloccato. Costruirlo è costato soldi veri e tante ore non pagate, e ci sono un'app Windows, un'app Android e un'app iOS che voglio rilasciare presto. Se ti è utile e vuoi aiutare con i costi di sviluppo e test, anche pochi euro in cripto lo fanno davvero andare avanti e, sinceramente, mi tengono motivato a continuare a costruirlo.",
    'NOOP is not a medical device. It is for informational and personal-insight purposes only and is not intended to diagnose, treat, cure or prevent any condition. Talk to a clinician for medical advice.': 'NOOP non è un dispositivo medico. Ha solo finalità informative e di conoscenza personale e non è destinato a diagnosticare, trattare, curare o prevenire alcuna condizione. Per consigli medici rivolgiti a un medico.',
    'NOOP pairs directly with your WHOOP over Bluetooth , no WHOOP app, no cloud.': 'NOOP si abbina direttamente al tuo WHOOP via Bluetooth, niente app WHOOP, niente cloud.',
    'NOOP scores your recovery, strain and sleep itself , on-device, no cloud.': 'NOOP calcola da sé il tuo recupero, carico e sonno, sul dispositivo, senza cloud.',
    'NOOP-computed': 'Calcolato da NOOP',
    'Normalized': 'Normalizzato',
    'Normalized overlay': 'Sovrapposizione normalizzata',
    'Not affiliated with, endorsed by, or connected to WHOOP. Interoperability software for hardware you own and your own data. Use it only with a device you own, and not in breach of any agreement that applies to you. Not a medical device.': 'Non affiliato, approvato o collegato a WHOOP. Software di interoperabilità per hardware di tua proprietà e per i tuoi dati. Usalo solo con un dispositivo di tua proprietà e senza violare alcun accordo a te applicabile. Non è un dispositivo medico.',
    'Not enough data for this window.': 'Dati insufficienti per questo intervallo.',
    'Not enough nights yet.': 'Ancora notti insufficienti.',
    'Not enough overlapping days between these metrics in %@. Widen the range.': "Giorni sovrapposti insufficienti tra queste metriche in %@. Amplia l'intervallo.",
    'Not enough overlapping history to correlate your metrics yet.': 'Cronologia sovrapposta ancora insufficiente per correlare le tue metriche.',
    'Not enough recent days to chart a trend yet. Import a history or keep wearing your strap.': 'Giorni recenti ancora insufficienti per tracciare un andamento. Importa una cronologia o continua a indossare la tua fascia.',
    'Not synced yet': 'Non ancora sincronizzato',
    'Nothing imported yet. On an iPhone: Health app, tap your photo, Export All Health Data, then import the .zip here in Data Sources.': 'Ancora nulla importato. Su iPhone: app Salute, tocca la tua foto, Esporta tutti i dati sulla salute, poi importa il file .zip qui in Sorgenti dati.',
    'Nothing in the catalog moves clearly with %@ over this window. Widen the range to surface relationships.': "Nessuna metrica del catalogo si muove chiaramente insieme a %@ in questo intervallo. Amplia l'intervallo per far emergere le relazioni.",
    'Nothing selected yet.': 'Ancora nulla di selezionato.',
    'Notifications': 'Notifiche',
    'of 3 · %@': 'di 3 · %@',
    'Off': 'Off',
    'Off , the coach answers generally and sends none of your metrics.': 'Off, il Coach risponde in modo generico e non invia nessuna delle tue metriche.',
    'OK': 'OK',
    'On , your recovery, sleep, HRV and workouts are shared with the provider for tailored coaching.': 'On, il tuo recupero, sonno, HRV e allenamenti vengono condivisi con il provider per un coaching su misura.',
    'On a 5/MG connection NOOP will send a puffin realtime-stream request after the handshake, and log what comes back. If you have a 5/MG strap, turning this on and sharing your strap log helps map the protocol. No effect on WHOOP 4.0.': "Con una connessione 5/MG, NOOP invierà una richiesta di flusso in tempo reale puffin dopo l'handshake e registrerà ciò che riceve. Se hai una fascia 5/MG, attivare questa opzione e condividere il registro della fascia aiuta a mappare il protocollo. Nessun effetto sulla WHOOP 4.0.",
    'Open-source BLE reverse-engineering work. Thank you.': 'Lavoro open-source di reverse engineering BLE. Grazie.',
    'Opens the GitHub releases page in your browser. NOOP itself makes no network connections , the macOS sandbox has no network entitlement.': "Apre la pagina delle release di GitHub nel tuo browser. NOOP di per sé non effettua alcuna connessione di rete, la sandbox di macOS non ha l'autorizzazione di rete.",
    'Outcome metric': 'Metrica di risultato',
    'Overlay': 'Sovrapposizione',
    'Overlay 2–4 signals': 'Sovrapponi 2–4 segnali',
    'Overlay signals, draw conclusions.': 'Sovrapponi i segnali, trai le conclusioni.',
    'p < 0.05': 'p < 0,05',
    'Paste your %@ API key': 'Incolla la tua chiave API di %@',
    'Pause': 'Pausa',
    'Paused': 'In pausa',
    'Peak': 'Picco',
    'Peaked': 'Al picco',
    'Pearson r': 'r di Pearson',
    'Pearson r · %@': 'r di Pearson · %@',
    'Pearson r over the visible window · |r| ≥ 0.30, n ≥ 10': "r di Pearson sull'intervallo visibile · |r| ≥ 0,30, n ≥ 10",
    'Points': 'Punti',
    'Profile': 'Profilo',
    'Provenance': 'Provenienza',
    'Provider': 'Provider',
    'Question': 'Domanda',
    'Questions, feedback, bugs , %@': 'Domande, feedback, bug, %@',
    'Quiet hours end': 'Fine ore di silenzio',
    'Quiet hours start': 'Inizio ore di silenzio',
    'r = %@': 'r = %@',
    'Re-scan': 'Scansiona di nuovo',
    'Readiness': 'Prontezza',
    'Reading your %@…': 'Lettura del tuo %@…',
    'Reading your Apple Health history…': 'Lettura della tua cronologia Apple Health…',
    'Reading your heart-rate variability and resting heart rate…': 'Lettura della variabilità della frequenza cardiaca e della frequenza cardiaca a riposo…',
    'Reading your history…': 'Lettura della tua cronologia…',
    'Reading your journal and outcomes…': 'Lettura del tuo diario e dei risultati…',
    'Ready': 'Pronto',
    'Ready to scan': 'Pronto per la scansione',
    'Recent moments': 'Momenti recenti',
    'Recompute': 'Ricalcola',
    'Record puffin frames to a file': 'Registra i frame puffin in un file',
    'Recovery': 'Recupero',
    "Recovery weighs your HRV against your personal baseline (~60%), resting heart rate (~20%), sleep performance (~15%) and respiration (~5%). Day strain is a 0–21 cardiovascular load from time in heart-rate zones. Sleep is staged from movement and heart rate. Everything is computed here from the strap's raw data , it works for any day NOOP collected raw streams.": 'Il recupero pesa il tuo HRV rispetto alla tua linea di base personale (~60%), la frequenza cardiaca a riposo (~20%), la prestazione del sonno (~15%) e la respirazione (~5%). Il carico giornaliero è un carico cardiovascolare da 0 a 21 basato sul tempo trascorso nelle zone di frequenza cardiaca. Il sonno viene suddiviso in fasi a partire da movimento e frequenza cardiaca. Tutto viene calcolato qui dai dati grezzi della fascia, funziona per qualsiasi giorno in cui NOOP ha raccolto i flussi grezzi.',
    'Refresh models': 'Aggiorna modelli',
    'Refresh models from provider': 'Aggiorna i modelli dal provider',
    'REM': 'REM',
    'Remove %@': 'Rimuovi %@',
    'Reset': 'Reimposta',
    'Reset API key': 'Reimposta chiave API',
    'Reset key': 'Reimposta chiave',
    'Respiratory': 'Respiratorio',
    'Respiratory rate': 'Frequenza respiratoria',
    'Rest': 'Riposo',
    'Restart': 'Riavvia',
    'Resting heart rate': 'Frequenza cardiaca a riposo',
    'Resting HR': 'FC a riposo',
    'Restorative': 'Rigenerante',
    'Reveal in Finder': 'Mostra nel Finder',
    'ROUND': 'GIRO',
    'Running': 'Corsa',
    'Save key': 'Salva chiave',
    'Save…': 'Salva…',
    'Saves every raw 5/MG frame (with a timestamp and the live heart rate) to a JSON file you can share to help map the biometric layout. This only records frames the strap already sent , it never writes to your strap , so it is safe to leave on. Export the file and attach it to a protocol-mapping issue.': 'Salva ogni frame grezzo 5/MG (con un timestamp e la frequenza cardiaca in diretta) in un file JSON che puoi condividere per aiutare a mappare la struttura biometrica. Registra solo i frame che la fascia ha già inviato, non scrive mai sulla tua fascia, quindi è sicuro lasciarlo attivo. Esporta il file e allegalo a una issue di mappatura del protocollo.',
    'Scan': 'Scansiona',
    'Scan & Connect': 'Scansiona e collega',
    'Scan with any %@ wallet': 'Scansiona con qualsiasi wallet %@',
    'Scanning…': 'Scansione…',
    'Searching': 'Ricerca in corso',
    'SECONDS': 'SECONDI',
    'Send': 'Invia',
    'Session': 'Sessione',
    'SESSION DONE': 'SESSIONE COMPLETATA',
    'Session live': 'Sessione in diretta',
    'Settings': 'Impostazioni',
    'Sex': 'Sesso',
    'Share of imported zone time, duration-weighted across sessions , approximate.': 'Quota del tempo importato per zona, ponderata per durata tra le sessioni, approssimativa.',
    'Should you push today?': 'Dovresti spingere oggi?',
    'Show %@ donation address': "Mostra l'indirizzo per donazioni %@",
    'SIGNIFICANT': 'SIGNIFICATIVO',
    'Silent haptic HIIT , the strap buzzes the transitions': 'HIIT aptico silenzioso, la fascia vibra alle transizioni',
    'Skip for now': 'Salta per ora',
    'Sleep': 'Sonno',
    'Sleep Debt': 'Debito di sonno',
    'Sleep Performance': 'Prestazione del sonno',
    'Sleep stage breakdown: deep %lld percent, light %lld percent, REM %lld percent, awake %lld percent': 'Dettaglio fasi del sonno: profondo %lld percento, leggero %lld percento, REM %lld percento, sveglio %lld percento',
    'Slow threads': 'Fili lenti',
    'Source Apple Health': 'Origine Apple Health',
    'Source Whoop': 'Origine Whoop',
    'Stage breakdown': 'Dettaglio fasi',
    'Stages vs typical': 'Fasi vs tipico',
    'Start': 'Avvia',
    'Start session': 'Avvia sessione',
    'State': 'Stato',
    'Steps': 'Passi',
    'Stop session': 'Termina sessione',
    'Strap': 'Fascia',
    'Strap bonded': 'Fascia abbinata',
    'STRAP LOG': 'REGISTRO FASCIA',
    'Strap not connected': 'Fascia non collegata',
    'Strap sync': 'Sincronizzazione fascia',
    'Stress': 'Stress',
    'Stress · %@': 'Stress · %@',
    'Stress · M': 'Stress · M',
    'Stress %@ of 3, %@': 'Stress %@ di 3, %@',
    'Stress is derived from two autonomic signals.': 'Lo stress deriva da due segnali autonomici.',
    'Stress monitor': 'Monitor dello stress',
    'Stress Trend': 'Andamento dello stress',
    'Suggested prompt: %@': 'Suggerimento proposto: %@',
    'Support': 'Supporto',
    'Support NOOP , donate or get in touch': 'Sostieni NOOP, fai una donazione o mettiti in contatto',
    'Support the build': 'Sostieni lo sviluppo',
    'Syncing strap history…': 'Sincronizzazione della cronologia della fascia…',
    'Test %@ buzz': 'Prova vibrazione %@',
    'Test action': 'Prova azione',
    'Test buzz': 'Prova vibrazione',
    'The thread of you over time.': 'Il filo di te nel tempo.',
    'These power your heart-rate zones, calorie estimates and recovery baselines. Keep them accurate.': 'Questi alimentano le tue zone di frequenza cardiaca, le stime caloriche e le linee di base del recupero. Mantienili accurati.',
    'Thinking': 'Sto pensando',
    'This builds from the strap as it syncs. Strain and sleep appear after you have worn it and slept a night. Recovery needs about a week of nights to learn your baseline, or import your WHOOP export to skip the wait.': "Si costruisce dalla fascia man mano che si sincronizza. Carico e sonno compaiono dopo che l'hai indossata e hai dormito una notte. Il recupero ha bisogno di circa una settimana di notti per apprendere la tua linea di base, oppure importa la tua esportazione WHOOP per evitare l'attesa.",
    'This is the only feature that leaves your Mac , it sends a summary of your metrics to %@ using your own key. Nothing is sent until you ask.': "Questa è l'unica funzione che lascia il tuo Mac, invia un riepilogo delle tue metriche a %@ usando la tua chiave. Nulla viene inviato finché non lo chiedi.",
    'This stands on community reverse-engineering. Huge thanks:': 'Questo si basa sul reverse engineering della community. Grazie di cuore:',
    'Time range': 'Intervallo di tempo',
    'to': 'a',
    'Today': 'Oggi',
    'Today’s Synthesis': 'Sintesi di oggi',
    "Today's value is your recorded daily stress score (0–3).": 'Il valore di oggi è il tuo punteggio di stress giornaliero registrato (0–3).',
    'Total Calories': 'Calorie totali',
    'Total Distance': 'Distanza totale',
    'Total Time': 'Tempo totale',
    'Total Workouts': 'Allenamenti totali',
    'Trend': 'Andamento',
    'Trends': 'Andamenti',
    'Trends need history to draw. Import your WHOOP export in Data Sources to see weeks, months and years instantly.': 'Gli andamenti hanno bisogno di una cronologia per essere tracciati. Importa la tua esportazione WHOOP in Sorgenti dati per vedere subito settimane, mesi e anni.',
    'Try again': 'Riprova',
    'Try WHOOP 5/MG protocol probes': 'Prova le sonde di protocollo WHOOP 5/MG',
    'Use': 'Usa',
    'Use custom model': 'Usa modello personalizzato',
    'v%@': 'v%@',
    'Visual only': 'Solo visivo',
    'Vital Signs': 'Segni vitali',
    'VO₂ Max': 'VO₂ Max',
    'Wake at': 'Sveglia alle',
    "We compare today's resting heart rate and HRV to your own 30-day baseline. A higher-than-usual resting HR and a lower-than-usual HRV both push the score up , classic signs the body is activated. The combined shift is mapped onto a 0–3 scale: 0 is calm, 1.5 sits at your baseline, 3 is highly activated.": "Confrontiamo la frequenza cardiaca a riposo e l'HRV di oggi con la tua linea di base di 30 giorni. Una FC a riposo più alta del solito e un HRV più basso del solito spingono entrambi il punteggio verso l'alto, segni classici di un corpo attivato. Lo spostamento combinato viene mappato su una scala 0–3: 0 è calmo, 1,5 corrisponde alla tua linea di base, 3 è altamente attivato.",
    'Weight': 'Peso',
    'What correlates': 'Cosa è correlato',
    'What moves your %@': 'Cosa influenza il tuo %@',
    'WHAT TO EXPECT': 'COSA ASPETTARSI',
    "What's new": 'Novità',
    'When I double-tap': 'Quando tocco due volte',
    'When the system prompt appears, choose Allow so NOOP can find your strap.': 'Quando appare la richiesta di sistema, scegli Consenti così NOOP può trovare la tua fascia.',
    'Which strap?': 'Quale fascia?',
    'Whoop': 'Whoop',
    'Whoop import': 'Importazione Whoop',
    "WHOOP straps don't appear in macOS System Settings → Bluetooth. They advertise on a custom profile that only apps like NOOP can find , so there's nothing to pair there, and you shouldn't try.": "Le fasce WHOOP non compaiono in Impostazioni di Sistema → Bluetooth su macOS. Si annunciano su un profilo personalizzato che solo app come NOOP possono trovare, quindi non c'è nulla da abbinare lì e non dovresti provarci.",
    'Window': 'Finestra',
    'With': 'Con',
    'Without': 'Senza',
    'Working…': 'Elaborazione…',
    'Workouts': 'Allenamenti',
    "Wrist delivery isn't live yet , it needs a small on-device watcher (coming in an update) to read macOS notifications. Everything stays on this Mac. Your choices are saved now and will apply automatically once delivery ships.": 'La consegna al polso non è ancora attiva, richiede un piccolo servizio sul dispositivo (in arrivo in un aggiornamento) per leggere le notifiche di macOS. Tutto resta su questo Mac. Le tue scelte sono salvate ora e verranno applicate automaticamente non appena la consegna sarà disponibile.',
    'You said: %@': 'Hai detto: %@',
    "You're connected.": 'Sei collegato.',
    'Your live heart rate is working from the strap, and recovery, strain and sleep build from it over your next few nights of wear, sharpening as it learns your baseline. Want your full history instantly? Import your WHOOP export in Data Sources and it backfills in about a minute.': 'La tua frequenza cardiaca in diretta funziona dalla fascia, e recupero, carico e sonno si costruiscono da essa nelle tue prossime notti di utilizzo, affinandosi man mano che apprende la tua linea di base. Vuoi subito la tua cronologia completa? Importa la tua esportazione WHOOP in Sorgenti dati e verrà ricostruita in circa un minuto.',
    'Your numbers, your strap, and how NOOP works. All on this Mac.': 'I tuoi numeri, la tua fascia e come funziona NOOP. Tutto su questo Mac.',
    'Your strap in real time , heart rate and frames as they arrive.': 'La tua fascia in tempo reale, frequenza cardiaca e frame man mano che arrivano.',
    'Your thread starts here.': 'Il tuo filo inizia qui.',
    'Zone': 'Zona',
    'Δ vs prev': 'Δ vs prec',
    'Fitness Age': 'Età fitness',
    'Vitality': 'Vitalità',
    'Skin Temp': 'Temp. pelle',
    'Hydration': 'Idratazione',
    'Heart-rate variability': 'Variabilità della frequenza cardiaca',
    'Breaths per minute': 'Respiri al minuto',
    'Autonomic load': 'Carico autonomico',
    'Updated weekly': 'Aggiornato settimanalmente',
    'Wellness score': 'Punteggio di benessere',
    'Skin temperature': 'Temperatura della pelle',
    "Today's fluid": 'Liquidi di oggi',
    'Charge': 'Carica',
    'Effort': 'Sforzo',
    'How Charge is calculated': 'Come viene calcolata la carica',
    'How Effort is calculated': 'Come viene calcolato lo sforzo',
    'How Rest is calculated': 'Come viene calcolato il riposo',
    'How Stress is calculated': 'Come viene calcolato lo stress',
    'Needs the strap': 'Richiede la fascia',
    'Building, wear it tonight': 'Creazione in corso, indossala stanotte',
    'Building, moves as you do': 'Creazione in corso, si muove con te',
    "After tonight's sleep": 'Dopo il sonno di stanotte',
    'Calibrating , %lld of %lld': 'Calibrazione, %lld di %lld',
}


def main() -> int:
    # encoding="utf-8" is load-bearing: on Windows the default cp1252 codec would
    # mojibake every accented character in the Italian copy.
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = catalog["strings"]

    missing: list[str] = []
    for key, entry in strings.items():
        if not key:
            continue
        value = IT.get(key)
        if value is None:
            missing.append(key)
            continue
        locs = entry.setdefault("localizations", {})
        locs["it"] = {"stringUnit": {"state": "translated", "value": value}}

    CATALOG.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")

    translated = sum(
        1 for k, v in strings.items()
        if k and "it" in v.get("localizations", {})
    )
    print(f"Italian units written: {translated}")
    if missing:
        print(f"MISSING ({len(missing)}):")
        for k in missing:
            print("  " + repr(k))
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
